---
- name: set root user password
  hosts: localhost
  vars:
    rootpassword: $6$z5DObQs7IJKBSCY4$ZX8IOOvlPIBwlu3tby2RJgNYT7JQoXepI2gyhssM.CirWaYVZ5Nu/gdIhpWcDBnJJwtfC7D7qvE13dHYHmuxo1
  
      tasks:
        user:
          name: root
          password: "{{rootpassword}}"
